package POO;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Juan Soto
 */
public class Menu extends javax.swing.JFrame {
public static String VCE="0";

DefaultTableModel model;
    Connection conn;
    Statement sent;
    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        String Nivel="1";
        Llenar();
        
        this.setMinimumSize(new Dimension(750, 200));
        setLocationRelativeTo(null);
        String nsql = "SELECT Nivel_administrativo from usuario WHERE Nombre='"
                +Login.users+"'";
        try{
            conn = Login.getConnection();
            sent = conn.createStatement();
            ResultSet rs = sent.executeQuery(nsql);
            Nivel = rs.getString(1);
            conn.close();
        }catch (Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
        if(Nivel.equals("0")){
            menuusuarios.setVisible(false);
            itemcancelarcita.setVisible(false);
            itemeliminarproducto.setVisible(false);
            itemeliminarmedicamento.setVisible(false);
            jMenuItem22.setVisible(false);
            itemeliminarcliente.setVisible(false);
            itemeditarmascota.setVisible(false);
            itemeliminarmascota.setVisible(false);
            
        }
    }
    void Llenar(){
        try {
            conn = Login.getConnection();
            String[] titulos ={"Folio","Cliente","Servicio","Dia","Hora","Pago","Método de pago"};
            String sql = "Select Folio,Cliente,Servicio,Dia,Hora,Pago,Tipo_pago from citas";
            model = new DefaultTableModel(null, titulos);
            sent = conn.createStatement();
            ResultSet rs = sent.executeQuery(sql);
            String[] fila = new String[7];
            while (rs.next()){
                fila[0]=rs.getString("Folio");
                fila[1]=rs.getString("Cliente");
                fila[2]=rs.getString("Servicio");
                fila[3]=rs.getString("Dia");
                fila[4]=rs.getString("Hora");
                fila[5]=rs.getString("Pago");
                fila[6]=rs.getString("Tipo_pago");
                
                model.addRow(fila);
            }
            jTable1.setModel(model);
            conn.close();
        } catch (Exception e){
            e.printStackTrace();
        }
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        servicios = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        menuinventario = new javax.swing.JMenu();
        menuproductos = new javax.swing.JMenu();
        itemnuevoproducto = new javax.swing.JMenuItem();
        itemeditarproducto = new javax.swing.JMenuItem();
        itemeliminarproducto = new javax.swing.JMenuItem();
        itemexistenciaproducto = new javax.swing.JMenuItem();
        menumedicamentos = new javax.swing.JMenu();
        itemnuevomedicamento = new javax.swing.JMenuItem();
        itemeditarmedicamento = new javax.swing.JMenuItem();
        itemeliminarmedicamento = new javax.swing.JMenuItem();
        itemexistenciamedicamento = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        clientes = new javax.swing.JMenu();
        itemnuevocliente = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        itemeliminarcliente = new javax.swing.JMenuItem();
        itemeditarcliente = new javax.swing.JMenuItem();
        menumascotas = new javax.swing.JMenu();
        itemnuevamascota = new javax.swing.JMenuItem();
        itemeditarmascota = new javax.swing.JMenuItem();
        itemeliminarmascota = new javax.swing.JMenuItem();
        itembuscarmascota = new javax.swing.JMenuItem();
        menucitas = new javax.swing.JMenu();
        itemnuevacita = new javax.swing.JMenuItem();
        itemeditarcita = new javax.swing.JMenuItem();
        itemcancelarcita = new javax.swing.JMenuItem();
        menuusuarios = new javax.swing.JMenu();
        itemnuevousuario = new javax.swing.JMenuItem();
        itemeditarusuario = new javax.swing.JMenuItem();
        itemeliminarusuario = new javax.swing.JMenuItem();
        itembuscarusuario = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Folio", "Cliente", "Servicio", "Día", "Hora", "Pago", "Método de pago"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        servicios.setText("Pagos");

        jMenuItem17.setText("Productos");
        servicios.add(jMenuItem17);

        jMenuItem16.setText("Servicios");
        servicios.add(jMenuItem16);

        jMenuBar1.add(servicios);

        menuinventario.setText("Inventario");
        menuinventario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuinventarioMouseClicked(evt);
            }
        });

        menuproductos.setText("Productos");

        itemnuevoproducto.setText("Nuevo producto");
        itemnuevoproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemnuevoproductoMouseClicked(evt);
            }
        });
        itemnuevoproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnuevoproductoActionPerformed(evt);
            }
        });
        menuproductos.add(itemnuevoproducto);

        itemeditarproducto.setText("Editar producto");
        itemeditarproducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemeditarproductoMouseClicked(evt);
            }
        });
        itemeditarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemeditarproductoActionPerformed(evt);
            }
        });
        menuproductos.add(itemeditarproducto);

        itemeliminarproducto.setText("Eliminar producto");
        itemeliminarproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemeliminarproductoActionPerformed(evt);
            }
        });
        menuproductos.add(itemeliminarproducto);

        itemexistenciaproducto.setText("Consultar existencia");
        itemexistenciaproducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemexistenciaproductoActionPerformed(evt);
            }
        });
        menuproductos.add(itemexistenciaproducto);

        menuinventario.add(menuproductos);

        menumedicamentos.setText("Medicamentos");

        itemnuevomedicamento.setText("Nuevo medicamento");
        itemnuevomedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnuevomedicamentoActionPerformed(evt);
            }
        });
        menumedicamentos.add(itemnuevomedicamento);

        itemeditarmedicamento.setText("Editar medicamento");
        itemeditarmedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemeditarmedicamentoActionPerformed(evt);
            }
        });
        menumedicamentos.add(itemeditarmedicamento);

        itemeliminarmedicamento.setText("Eliminar medicamento");
        itemeliminarmedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemeliminarmedicamentoActionPerformed(evt);
            }
        });
        menumedicamentos.add(itemeliminarmedicamento);

        itemexistenciamedicamento.setText("Consultar existencia");
        itemexistenciamedicamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemexistenciamedicamentoActionPerformed(evt);
            }
        });
        menumedicamentos.add(itemexistenciamedicamento);

        menuinventario.add(menumedicamentos);

        jMenu2.setText("Servicios");

        jMenuItem1.setText("Nuevo servicio");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuItem2.setText("Editar servicio");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Eliminar servicio");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        menuinventario.add(jMenu2);

        jMenuBar1.add(menuinventario);

        clientes.setText("Clientes");
        clientes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clientesMouseClicked(evt);
            }
        });
        clientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientesActionPerformed(evt);
            }
        });

        itemnuevocliente.setText("Nuevo cliente");
        itemnuevocliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itemnuevoclienteMouseClicked(evt);
            }
        });
        itemnuevocliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnuevoclienteActionPerformed(evt);
            }
        });
        clientes.add(itemnuevocliente);

        jMenuItem22.setText("Editar cliente");
        jMenuItem22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem22ActionPerformed(evt);
            }
        });
        clientes.add(jMenuItem22);

        itemeliminarcliente.setText("Eliminar cliente");
        itemeliminarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemeliminarclienteActionPerformed(evt);
            }
        });
        clientes.add(itemeliminarcliente);

        itemeditarcliente.setText("Buscar cliente");
        itemeditarcliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemeditarclienteActionPerformed(evt);
            }
        });
        clientes.add(itemeditarcliente);

        jMenuBar1.add(clientes);

        menumascotas.setText("Mascotas");

        itemnuevamascota.setText("Añadir mascota");
        itemnuevamascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnuevamascotaActionPerformed(evt);
            }
        });
        menumascotas.add(itemnuevamascota);

        itemeditarmascota.setText("Editar mascota");
        itemeditarmascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemeditarmascotaActionPerformed(evt);
            }
        });
        menumascotas.add(itemeditarmascota);

        itemeliminarmascota.setText("Eliminar mascota");
        itemeliminarmascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemeliminarmascotaActionPerformed(evt);
            }
        });
        menumascotas.add(itemeliminarmascota);

        itembuscarmascota.setText("Buscar mascota");
        itembuscarmascota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itembuscarmascotaActionPerformed(evt);
            }
        });
        menumascotas.add(itembuscarmascota);

        jMenuBar1.add(menumascotas);

        menucitas.setText("Citas");

        itemnuevacita.setText("Nueva cita");
        itemnuevacita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnuevacitaActionPerformed(evt);
            }
        });
        menucitas.add(itemnuevacita);

        itemeditarcita.setText("Editar cita");
        itemeditarcita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemeditarcitaActionPerformed(evt);
            }
        });
        menucitas.add(itemeditarcita);

        itemcancelarcita.setText("Cancelar cita");
        itemcancelarcita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemcancelarcitaActionPerformed(evt);
            }
        });
        menucitas.add(itemcancelarcita);

        jMenuBar1.add(menucitas);

        menuusuarios.setText("Usuarios");

        itemnuevousuario.setText("Añadir usuario");
        itemnuevousuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemnuevousuarioActionPerformed(evt);
            }
        });
        menuusuarios.add(itemnuevousuario);

        itemeditarusuario.setText("Editar usuario");
        itemeditarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemeditarusuarioActionPerformed(evt);
            }
        });
        menuusuarios.add(itemeditarusuario);

        itemeliminarusuario.setText("Eliminar usuario");
        itemeliminarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemeliminarusuarioActionPerformed(evt);
            }
        });
        menuusuarios.add(itemeliminarusuario);

        itembuscarusuario.setText("Buscar usuario");
        itembuscarusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itembuscarusuarioActionPerformed(evt);
            }
        });
        menuusuarios.add(itembuscarusuario);

        jMenuBar1.add(menuusuarios);

        jMenu1.setText("Salir");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 563, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientesActionPerformed
    }//GEN-LAST:event_clientesActionPerformed

    private void clientesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clientesMouseClicked

    }//GEN-LAST:event_clientesMouseClicked

    private void itemnuevoclienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemnuevoclienteMouseClicked
    }//GEN-LAST:event_itemnuevoclienteMouseClicked

    private void itemnuevoclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnuevoclienteActionPerformed
        // TODO add your handling code here:
        VCE="1";
        new Gestionclientes().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemnuevoclienteActionPerformed

    private void itemnuevacitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnuevacitaActionPerformed
        // TODO add your handling code here:
        VCE="1";
        new Generarcita().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemnuevacitaActionPerformed

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMenu1MouseClicked

    private void menuinventarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuinventarioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuinventarioMouseClicked

    private void itemnuevoproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemnuevoproductoMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_itemnuevoproductoMouseClicked

    private void itemeditarproductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itemeditarproductoMouseClicked

    }//GEN-LAST:event_itemeditarproductoMouseClicked

    private void itemnuevoproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnuevoproductoActionPerformed
        // TODO add your handling code here:
        VCE="1";
        new Gestionproductos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemnuevoproductoActionPerformed

    private void itemeditarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemeditarproductoActionPerformed
        // TODO add your handling code here:
        VCE="2";
        new Gestionproductos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemeditarproductoActionPerformed

    private void itemnuevomedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnuevomedicamentoActionPerformed
        // TODO add your handling code here:
        VCE="1";
        new Gestionmedicamentos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemnuevomedicamentoActionPerformed

    private void itemeditarmedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemeditarmedicamentoActionPerformed
        // TODO add your handling code here:
        VCE="2";
        new Gestionmedicamentos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemeditarmedicamentoActionPerformed

    private void itemnuevousuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnuevousuarioActionPerformed
        // TODO add your handling code here:
        VCE="1";
        new Gestionusuarios().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemnuevousuarioActionPerformed

    private void itemeditarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemeditarusuarioActionPerformed
        // TODO add your handling code here:
        VCE="2";
        new Gestionusuarios().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemeditarusuarioActionPerformed

    private void itemeditarcitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemeditarcitaActionPerformed
        // TODO add your handling code here:
        VCE="2";
        new Generarcita().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemeditarcitaActionPerformed

    private void itemcancelarcitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemcancelarcitaActionPerformed
        // TODO add your handling code here:
        VCE="3";
        new Generarcita().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemcancelarcitaActionPerformed

    private void itemnuevamascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemnuevamascotaActionPerformed
        // TODO add your handling code here:
        VCE="1";
        new Gestionmascotas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemnuevamascotaActionPerformed

    private void itemeditarmascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemeditarmascotaActionPerformed
        // TODO add your handling code here:
        VCE="2";
        new Gestionmascotas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemeditarmascotaActionPerformed

    private void itemeliminarmascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemeliminarmascotaActionPerformed
        // TODO add your handling code here:
        VCE="3";
        new Gestionmascotas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemeliminarmascotaActionPerformed

    private void itembuscarmascotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itembuscarmascotaActionPerformed
        // TODO add your handling code here:
        VCE="4";
        new Gestionmascotas().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itembuscarmascotaActionPerformed

    private void itembuscarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itembuscarusuarioActionPerformed
        // TODO add your handling code here:
        VCE="4";
        new Gestionusuarios().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itembuscarusuarioActionPerformed

    private void itemeliminarusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemeliminarusuarioActionPerformed
        // TODO add your handling code here:
        VCE="3";
        new Gestionusuarios().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemeliminarusuarioActionPerformed

    private void jMenuItem22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem22ActionPerformed
        // TODO add your handling code here:
        VCE="2";
        new Gestionclientes().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem22ActionPerformed

    private void itemeliminarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemeliminarclienteActionPerformed
        // TODO add your handling code here:
        VCE="3";
        new Gestionclientes().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemeliminarclienteActionPerformed

    private void itemeditarclienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemeditarclienteActionPerformed
        // TODO add your handling code here:
        VCE="4";
        new Gestionclientes().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemeditarclienteActionPerformed

    private void itemeliminarproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemeliminarproductoActionPerformed
        // TODO add your handling code here:
        VCE="3";
        new Gestionproductos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemeliminarproductoActionPerformed

    private void itemeliminarmedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemeliminarmedicamentoActionPerformed
        // TODO add your handling code here:
        VCE="3";
        new Gestionmedicamentos().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemeliminarmedicamentoActionPerformed

    private void itemexistenciaproductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemexistenciaproductoActionPerformed
        // TODO add your handling code here:
        VCE="P";
        new Existencias().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemexistenciaproductoActionPerformed

    private void itemexistenciamedicamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemexistenciamedicamentoActionPerformed
        // TODO add your handling code here:
        VCE="M";
        new Existencias().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_itemexistenciamedicamentoActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        VCE="2";
        new Gestionservicios().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        VCE="1";
        new Gestionservicios().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        VCE="3";
        new Gestionservicios().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu clientes;
    private javax.swing.JMenuItem itembuscarmascota;
    private javax.swing.JMenuItem itembuscarusuario;
    private javax.swing.JMenuItem itemcancelarcita;
    private javax.swing.JMenuItem itemeditarcita;
    private javax.swing.JMenuItem itemeditarcliente;
    private javax.swing.JMenuItem itemeditarmascota;
    private javax.swing.JMenuItem itemeditarmedicamento;
    private javax.swing.JMenuItem itemeditarproducto;
    private javax.swing.JMenuItem itemeditarusuario;
    private javax.swing.JMenuItem itemeliminarcliente;
    private javax.swing.JMenuItem itemeliminarmascota;
    private javax.swing.JMenuItem itemeliminarmedicamento;
    private javax.swing.JMenuItem itemeliminarproducto;
    private javax.swing.JMenuItem itemeliminarusuario;
    private javax.swing.JMenuItem itemexistenciamedicamento;
    private javax.swing.JMenuItem itemexistenciaproducto;
    private javax.swing.JMenuItem itemnuevacita;
    private javax.swing.JMenuItem itemnuevamascota;
    private javax.swing.JMenuItem itemnuevocliente;
    private javax.swing.JMenuItem itemnuevomedicamento;
    private javax.swing.JMenuItem itemnuevoproducto;
    private javax.swing.JMenuItem itemnuevousuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu menucitas;
    private javax.swing.JMenu menuinventario;
    private javax.swing.JMenu menumascotas;
    private javax.swing.JMenu menumedicamentos;
    private javax.swing.JMenu menuproductos;
    public javax.swing.JMenu menuusuarios;
    private javax.swing.JMenu servicios;
    // End of variables declaration//GEN-END:variables
}
